version: "3.8"

volumes:
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: datapoint_production_django
    restart: always
    volumes:
      - production_django_media:/app/media
    env_file:
      - .env
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: datapoint_production_nginx
    restart: always
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - production_django_media:/usr/share/nginx/media
